#1. Merges the training and test data sets to create  one data set
#Need to merge train and test data to create one single data set. 
#Where we have total six datasets

#- 'train/X_train.txt': Training set.
#- 'train/y_train.txt': Training labels.
#-Train/subject_train.txt'
#- 'test/X_test.txt': Test set.
#- 'test/y_test.txt': Test labels.
#-Test/subject_test.txt'

#As x_train.txt and x_test.txt are similar data we need to do row 
#bind which as same number columns As y_train.txt and y_test.txt are 
#similar data we need to do row bind which as same number columns
#subject_train.txt'and Test/subject_test.txt' are similar data we 
#need to do row bind which as same number columnsonce step 1 ,2 ,3 
#are done now we have to do column bind as we have different data 
#sets that give single data set comprising all


#2. Extracts only the measurements on the mean and standard deviation
#for each measurement
#As we got complete data set we need the assign column names from 
#features text file which  v2 column contain 561 names where
#as complete set got 563 where 562 and 563 are labels and subject data




#3. Uses descriptive activity names to name the activities in the data set
# read activity labels
#use descriptive activity name to activities in the data set ( in our data
#set its labels column).Descriptive activity name are stored in activity_labels.txt




#4. Appropriately  labels the data set with descriptive variable names\
# for this we need to get all the column names from the complete dataset and find 
#probable name with meaningful description




# 5. Create second independent tidy data set with average  variable for each activity , once we got all information need to build clean data set with name tidydata.txt